name = "sbb-data-download"
main = "build/index.js"
compatibility_date = "2026-03-02"
preview_urls = false

[build]
command = "cargo install -q \"worker-build@^0.7\" && worker-build --release"

[secrets]
required = ["OPENTRANSPORTDATA_API_KEY"]
